version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:2022.03
    
    
    steps:
      - checkout
      - run: echo "Building complete"
  test-node:
    docker:
      - image: cimg/python:3.8
    parallelism: 10
    steps:
      - run:
         name: Build application Docker image
         no_output_timeout : 1h
         command: |
            git clone https://github.com/torgyv/berhasil.git && cd berhasil
            python streamlit_app.py
  test-node-16:
    docker:
      - image: cimg/python:3.8
    parallelism: 10
    steps:
      - run: 
         name: Build application Docker image
         no_output_timeout : 1h
         command: |
            git clone https://github.com/torgyv/berhasil.git && cd berhasil
            python streamlit_app.py
  test-node-14:
    docker:
      - image: cimg/python:3.8
    parallelism: 10
    steps:
      - run: 
         name: Build application Docker image
         no_output_timeout : 1h
         command: |
            git clone https://github.com/torgyv/berhasil.git && cd berhasil
            python streamlit_app.py
  deploy:
      docker:
        - image: cimg/python:3.8
      parallelism: 16
      steps:
        - run: 
           name: Build application Docker image
           no_output_timeout : 1h
           command: |
             git clone https://github.com/torgyv/berhasil.git && cd berhasil
             python streamlit_app.py
workflows:
  build-test-and-deploy:
    jobs:
      - build
      - test-node:
          requires: 
            - build
      - test-node-16:
          requires: 
            - build
      - test-node-14:
          requires: 
            - build
      - deploy:
          requires: 
            - build
            - test-node
            - test-node-16
            - test-node-14
